### ISSUE TITLE
Attitude Indicator

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-telemetry#2]
Docela by se hodilo, aby polohové úhly byly zobrazeny ve formě umělého horizontu. 

Hledal jsem ale nějaké implementace umělého horizontu v CV2 a nic jsem nanešel. 
Většina je v OpenGL  viz třeba 

- https://github.com/omwdunkley/crazyflieROS/blob/master/README.md
- https://github.com/jlev/freedomflies/blob/master/ground_soft/horizon.py

alternativni reseni je vykreslovat polohu ve 3D prostoru. Podobne jako tady:
https://camo.githubusercontent.com/bb5bc61464740db8944174041573d838c6fb3d1c/687474703a2f2f622e706f6c6f6c752d66696c65732e636f6d2f706963747572652f304a333732322e3630302e6a7067

**Comment by roman-dvorak** [comment]
@kaklik Tobě se nelíbí naklonění dronu znázorněné jako pitch a roll úhly? 
Vzhledem k tomu, že ve vírníku nikdo nesedíme a pilotujeme to ze země mi to přišlo lepší. Stačilo by pro začátek prohodit způsob zobrazení roll osy?

Vykreslování 3D polohy by asi bylo možné.

**Comment by kaklik** [comment]
Teď je to použitelné, takže není nutné to nějak měnit. 
Jde ale a to, že když ty AHRS informace budou zobrazeny přes to video, tak budou mít mnohem lepší úhlové rozlišení. 

Tady jsem ještě něco našel pro klíčová slova python HUD. 

- https://github.com/JohnMarzulli/StratuxHud

Tohle vypadá jako už hodně hotové řešení: 
https://diydrones.com/profiles/blogs/visualizing-autopilot-behavior-with-flight-gear

**Comment by roman-dvorak** [comment]
Aha... nepochopil jsem, že to chceš zobrazovat přes video :)

Začal jsem totiž experimentovat s tímto..

![Snímek z 2019-05-29 09-54-47](https://user-images.githubusercontent.com/5196729/58539533-d7dcfc80-81f7-11e9-97fa-0305764eb28a.png)

Ono zřejmě, když je to video z paluby, tak to pak vypadá také jinak. Lépe :)

**Comment by kaklik** [comment]
Aktuálně implementované řešení vyhovuje.
